version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/terraform:/app/terraform
    # Uncomment the next two lines if running locally and you want to pass host AWS creds:
    # - ~/.aws:/root/.aws:ro
    # environment:
    #   - AWS_PROFILE=default

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
